### ISSUE TITLE
ckeditor is not being checked.

### ISSUE THREAD

**Issue by web010** [fusionbox/jquery-dontJustLeaveMe#1]
If a page contains multiple forms, a changed form cannot be submitted. All forms are checked and when the last form in the checker was not the submitted one, the checker gives a 'false' on 'was_submitted' and a true on 'changed input', which results in the returnmessage.

Second problem is the checking of an editor which might be part of the form. I solved this by adding the options with "editor:check_editor". check_editor (default=false) is a callback function in a custom script. In the function dontJustLeaveMe I made the following change:
$(window).on('beforeunload', function() {
   if ( ! was_submitted && options.editor){ 
      dirty_editor = options.editor();
   }
   if ( ! was_submitted && (dirty_editor || options.serializeForm($form) != initialState) ){
      return options.errorMessage;
   }
 });

**Comment by rockymeza** [comment]
Hi @web010,

Thanks for reporting these!  I'm going to split this issues up in to 2 so that we can keep track of them separately.  the multiple forms bug now lives at #2.  This bug will be about CKEditors (I changed the title if that's ok with you).
