### ISSUE TITLE
multiple forms give conflict

### ISSUE THREAD

**Issue by rockymeza** [fusionbox/jquery-dontJustLeaveMe#2]
[reported by @web010]

> If a page contains multiple forms, a changed form cannot be submitted. All forms are checked and when the last form in the checker was not the submitted one, the checker gives a 'false' on 'was_submitted' and a true on 'changed input', which results in the returnmessage.

**Comment by gavinwahl** [comment]
I don't think this is a bug -- when there are multiple forms on the page, and you are submitting a different form than the one you have edited, the data you edited isn't going to be submitted.
